// <auto-generated />
using System;
using InterviewProject.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewProject.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230212141543_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InterviewProject.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = ".Net 6 Eğitimi"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Mikroservis Mimarisi"
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "İş Analisti"
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Python"
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "SAP Danışmanlığı"
                        });
                });

            modelBuilder.Entity("InterviewProject.Entities.CourseStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CourseStudents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 4,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 3,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 3,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 5,
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("InterviewProject.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1996, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Seda",
                            LastName = "KELEŞ"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1992, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Batuhan",
                            LastName = "GÜN"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1996, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Can",
                            LastName = "KARABULUT"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1996, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Serhat",
                            LastName = "ÜNAL"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1996, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Selma",
                            LastName = "YALÇIN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
